### ISSUE TITLE
runtimeLoader: mismatch between dev-service-runtime and dev-browser-runtime

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-service-framework#31] opened 2016-03-18 19:39 UTC
Currently runtimeLoader implementations are different and not compatible in dev-service-runtime and dev-browser-runtime. 

@dvilchez @vitormsilva pls reach an agreement for a common/compliant implementation, asap.

**Comment by vitormsilva** [comment] 2016-03-28 09:11
Hi @dvilchez,

After a strong analyse, we did a sequence diagram to optimise, have a consensus, something all can follow and close this problem;

I will ask to you to analyse the following diagram and say your opinion.

![runtime-browser](https://cloud.githubusercontent.com/assets/10596749/14074987/272a811a-f4cd-11e5-9953-31266ed6f13f.png)

I will waiting for some feedback.

**Comment by dvilchez** [comment] 2016-03-28 14:07
Hi @vitormsilva,

I am going to highlight some doubts for me after checking your diagram:

In 3, minibus comes in the rethink bundle, not as a separated file. Are you specifying this because your runtime loader implementation?

In 4, too much responsibility for a constructor in my opinion. As you know from my views we do not even need a constructor but in case we need one I think it is doing more than only construct the runtime-loader object which responsibility is to return specific runtime implementation. 

From 5 to 11, from my point of view all these tasks are installation tasks, anyway is required to notifty when iframe is loaded before sending new messages in 14.

**Comment by vitormsilva** [comment] 2016-03-29 10:59
@dvilchez,

> In 3, minibus comes in the rethink bundle, not as a separated file. Are you specifying this because your runtime loader implementation?

yes, but we decided separately only for we don't forget to include in that bundle the components we need;

> In 4, too much responsibility for a constructor in my opinion. As you know from my views we do not even need a constructor but in case we need one I think it is doing more than only construct the runtime-loader object which responsibility is to return specific runtime implementation. 

I don't understand what you want to say with this, but this constructor needs to be responsible for creating the iframe component;

> From 5 to 11, from my point of view all these tasks are installation tasks, anyway is required to notifty when iframe is loaded before sending new messages in 14.

yes, I agree with you, is necessary send a response to the user with something, like, "ready";

Can you post here the sequence diagram with your changes?

**Comment by dvilchez** [comment] 2016-03-30 14:24
I tried to show how it is working on my current implementation.
![runtime-browser](https://cloud.githubusercontent.com/assets/153025/14145370/ea1070e6-f693-11e5-8d39-337eb0dfecc4.png)

**Comment by shumy** [comment] 2016-03-30 14:54
There is a requirement of getting "device capabilities" and install the runtime accordingly. It should be in the flow somehow.
I also don't understand steps 12 and 13. Shouldn't the descriptor get the RuntimeUA (code or ref)? And so, should it be before the RuntimUA instantiation.

**Comment by vitormsilva** [comment] 2016-03-30 15:24
@dvilchez,

What is the content of rethink.js (step 2) and core.js (step 8)?

We think you have some problems here:
 - where you get the device capabilities?
 - can you explain the steps 11 - 14?
   - step 11 - you instantiate the RuntimeUA?
   - step 12 - and you get the RuntimeUA again?

   shouldn't be the step 12 - 13 first, and only after that, you can instantiate the RuntimeUA.

Maybe the bootstrap messages can be routed without the MiniBus. But all other should be transmitted in the already defined routing system. The MiniBus is an instance that is passed to the hyperties, and in that way, it should be independent of the implementation.

I think all installation process should be through messages, that is not happening here but @pchainho should confirm this, also, if you have an hyperty on WebApp side you will need the minibus to send the message to that hyperty;

**Comment by dvilchez** [comment] 2016-03-31 10:29
@vitormsilva, @shumy 

You are right I made a mistake with 12 and 13, I corrected it in the updated diagram. In addition, I added a note with core.js and rethink.js content.

@shumy I tried to represent the actual implementation and some agreements that we reached in our last visit to Aveiro. I wasn't aware of  device capabilities requirement until now and I don't know how to pass it to Runtime, some references to documentation will be appreciated. In any case, I think this is another discussion.

> Maybe the bootstrap messages can be routed without the MiniBus. But all other should be transmitted in the already defined routing system. 

I think application developer calls hyperty methods directly without messages.

>The MiniBus is an instance that is passed to the hyperties, and in that way, it should be independent of the implementation.

I agree.

>I think all installation process should be through messages, that is not happening here but @pchainho should confirm this

Maybe the problem is defining what is the installation process. From my views, setting up all the message infrastructure is part of the installation process and not should be on a constructor.
![runtime-browser](https://cloud.githubusercontent.com/assets/153025/14173089/2f0cbdfa-f73c-11e5-9fe1-09a407a94dfd.png)

**Comment by vitormsilva** [comment] 2016-04-04 11:51
Hi @dvilchez,

I agree with your proposal, for me you can proceed with it;

But I have some observation points:
 - we will need to get the get-devices-capabilites, this is referenced on DataModel, [here](https://github.com/reTHINK-project/dev-service-framework/blob/develop/docs/datamodel/hyperty-catalogue/readme.md#hyperty-runtime-descriptor)
 - the "sandboxFactory" need to be an "runtimeFactory", because the core will not using it only for create a sandbox but also, have an function to define the type of HttpRequest done, you can see [RuntimeFactory](https://github.com/reTHINK-project/dev-service-framework/blob/develop/resources/factories/RuntimeFactory.js#L27)

After you implemented the changes, let me know, for apply the runtime-browser to the hyperty toolkit.

**Comment by dvilchez** [comment] 2016-04-04 14:20
Ok, I will create two issues to cover these requirements. 

By the way, @vitormsilva,  I find out runtime is getting descriptors from root path instead of well-known URI, maybe is something you can fix.

**Comment by vitormsilva** [comment] 2016-04-04 15:09
Can you explain better? Could you share a print-screen or something to help me find the problem?
Thanks

**Comment by vitormsilva** [comment] 2016-04-07 08:26
@dvilchez, the problem reported before was solved? can I close this issue?

**Comment by dvilchez** [comment] 2016-04-07 09:42
@vitormsilva Yes, you can

**Closed** 2016-04-07 09:42 UTC
Labels: bug
