### ISSUE TITLE
RuntimeCatalogue Issue/Doubts

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-service-framework#32] opened 2016-04-11 14:49 UTC
Hi @Endebert,

In line [299 of RuntimeCatalogue](https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/runtime-catalogue/RuntimeCatalogue.js#L299), this code `_this._factory.createSourcePackage()` shouldn't be `_this._factory.createSourcePackage()`?

My doubt is when you have a sourcePackageURL and it's an external URL to get the descriptor, the process to get that sourcePackage should be done by the catalogue, and return all the descriptor;

**Comment by pchainho** [comment] 2016-04-12 14:12
pls give priority to this issue that is blocking integration with the catalogue

**Comment by Endebert** [comment] 2016-04-14 09:31
Could you please elaborate, what the problem is?

You can get the sourcePackage easily by using the function `getSourcePackageFromURL()`.

The sourcePackage is not automatically download with the descriptor to optimize traffic and only load (potentially large) sourcePackages when needed.

If you want the sourcePackage of a descriptor, I'm assuming a one-liner like this should work:

`var sourcePackage = descriptor.sourcePackage || catalogue.getSourcePackageFromURL(descriptor.sourcePackageURL)`

Alternatively, if you only need the sourceCode, you can use `getSourceCodeFromDescriptor(descriptor)`.

**Comment by vitormsilva** [comment] 2016-04-14 09:54
My mistake, I wrote in the wrong way, sorry. I will explain better;

In line [299](https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/runtime-catalogue/RuntimeCatalogue.js#L299) you have `let sourcePackage = _this.factory.createSourcePackage(sp["sourceCodeClassname"], sp["sourceCode"]);` this code, but the factory is not defined like this, is defined in this way `_this._factory`. 

You can check the line [11](https://github.com/reTHINK-project/dev-service-framework/blob/develop/src/runtime-catalogue/RuntimeCatalogue.js#L11)

Ok, I will open an issue with this for runtime-core, and will check if the runtime-browser need to that changes too;

**Comment by emmelmann-fokus** [comment] 2016-04-14 09:58
@vitormsilva,  does your response mean that we can close this issue or assign it to someone else.  From the discussion, I read that @Endebert does not have to take further actions.

Apologies for trying to be clear on who is working / has to work on this; but we have internally to carefully assign resources and if I can take this off of Robert's shoulders, I'd like to do that :-)

@vitormsilva please close this or reassign (if required back to Robert).

**Comment by vitormsilva** [comment] 2016-04-14 10:04
@emmelmann-fokus,

The first part is for @Endebert , because need to fix what i explain;
> In line 299 you have let sourcePackage = _this.factory.createSourcePackage(sp["sourceCodeClassname"], sp["sourceCode"]); this code, but the factory is not defined like this, is defined in this way _this._factory.

You can check the line 11

---
The other part is for me, because i need to make some changes;

> Ok, I will open an issue with this for runtime-core, and will check if the runtime-browser need to that changes too;


I assume can close this issue when the part of @Endebert was done;

**Comment by emmelmann-fokus** [comment] 2016-04-14 10:07
@vitormsilva thanks for the clarification.

@Endebert will close this issue once his part is done.

**Comment by Endebert** [comment] 2016-04-14 10:50
@vitormsilva thanks for the clarification. Because in your initial description both code lines are identical, I didn't realize you were pointing to the missing underscore. I fixed it in this commit: https://github.com/reTHINK-project/dev-service-framework/commit/bf70bb5d5bb8da528899826ba672e4712bf7a4ca

**Closed by Endebert** 2016-04-14 10:50 UTC
Labels: help wanted, question
